window.ISO_AUDIT_CONTROLS = [
  {id:"4.1",d:"4",t:"Compréhension de l'organisme",desc:"Déterminer les enjeux internes et externes pertinents à le SMSI.",hds:false},
  {id:"4.2",d:"4",t:"Parties intéressées",desc:"Identifier les parties intéressées et leurs exigences vis-à-vis du SMSI.",hds:true},
  {id:"4.3",d:"4",t:"Domaine d'application",desc:"Définir le périmètre du SMSI avec limites et applicabilité.",hds:false},
  {id:"4.4",d:"4",t:"Système de management",desc:"Établir, mettre en œuvre, maintenir et améliorer le SMSI.",hds:false},
  {id:"5.1",d:"5",t:"Leadership et engagement",desc:"La direction fait preuve de leadership et d'engagement envers le SMSI.",hds:false},
  {id:"5.2",d:"5",t:"Politique de sécurité",desc:"Politique SSI approuvée par la direction, communiquée et disponible.",hds:true},
  {id:"5.3",d:"5",t:"Rôles et responsabilités",desc:"Rôles et responsabilités SSI attribués et communiqués.",hds:false},
  {id:"6.1",d:"6",t:"Risques et opportunités",desc:"Déterminer les risques et opportunités à adresser par le SMSI.",hds:false},
  {id:"6.1.2",d:"6",t:"Appréciation des risques",desc:"Processus documenté d'identification, analyse et évaluation des risques SSI.",hds:true},
  {id:"6.1.3",d:"6",t:"Traitement des risques",desc:"Sélectionner les options de traitement et établir la Déclaration d'Applicabilité (SoA).",hds:true},
  {id:"6.2",d:"6",t:"Objectifs de sécurité",desc:"Objectifs SSI mesurables et cohérents avec la politique.",hds:false},
  {id:"7.1",d:"7",t:"Ressources",desc:"Déterminer et fournir les ressources nécessaires à le SMSI.",hds:false},
  {id:"7.2",d:"7",t:"Compétences",desc:"Compétences requises déterminées, acquises et démontrées.",hds:false},
  {id:"7.3",d:"7",t:"Sensibilisation",desc:"Personnel sensibilisé à la politique SSI, sa contribution et aux conséquences.",hds:false},
  {id:"7.4",d:"7",t:"Communication",desc:"Communication interne et externe SSI définie et maîtrisée.",hds:false},
  {id:"7.5",d:"7",t:"Information documentée",desc:"Documents requis créés, mis à jour et maîtrisés selon les exigences.",hds:true},
  {id:"8.1",d:"8",t:"Planification opérationnelle",desc:"Processus du SMSI planifiés, mis en œuvre et contrôlés.",hds:false},
  {id:"8.2",d:"8",t:"Appréciation des risques",desc:"Appréciation des risques réalisée selon la fréquence planifiée.",hds:false},
  {id:"8.3",d:"8",t:"Traitement des risques",desc:"Plan de traitement des risques SSI mis en œuvre.",hds:false},
  {id:"9.1",d:"9",t:"Surveillance et mesure",desc:"Performances SSI et efficacité du SMSI évaluées.",hds:false},
  {id:"9.2",d:"9",t:"Audit interne",desc:"Audits internes réalisés à intervalles planifiés.",hds:false},
  {id:"9.3",d:"9",t:"Revue de direction",desc:"Direction revue le SMSI à intervalles planifiés.",hds:false},
  {id:"10.1",d:"10",t:"Non-conformité et actions correctives",desc:"Réaction aux NC et actions correctives documentées et efficaces.",hds:false},
  {id:"10.2",d:"10",t:"Amélioration continue",desc:"Amélioration continue de la pertinence et l'efficacité du SMSI.",hds:false},
  {id:"A.5.1",d:"A5",t:"Politiques de sécurité",desc:"Politiques approuvées, publiées, communiquées et revues.",hds:true},
  {id:"A.5.2",d:"A5",t:"Rôles et responsabilités SSI",desc:"Responsabilités SSI définies et attribuées.",hds:false},
  {id:"A.5.3",d:"A5",t:"Séparation des tâches",desc:"Tâches conflictuelles séparées pour réduire le risque.",hds:true},
  {id:"A.5.4",d:"A5",t:"Responsabilités de la direction",desc:"Direction exige le respect de la politique SSI.",hds:false},
  {id:"A.5.5",d:"A5",t:"Contact avec les autorités",desc:"Contacts appropriés maintenus avec les autorités.",hds:false},
  {id:"A.5.6",d:"A5",t:"Contact groupes spécialisés",desc:"Contacts avec groupes spécialisés en SSI.",hds:false},
  {id:"A.5.7",d:"A5",t:"Threat intelligence",desc:"Informations relatives aux menaces SSI collectées et analysées.",hds:false},
  {id:"A.5.8",d:"A5",t:"SSI dans la gestion de projet",desc:"SSI intégrée dans la gestion de projet.",hds:false},
  {id:"A.5.9",d:"A5",t:"Inventaire des actifs",desc:"Actifs SSI identifiés, inventoriés et maintenus.",hds:true},
  {id:"A.5.10",d:"A5",t:"Utilisation acceptable des actifs",desc:"Règles d'utilisation acceptable des actifs définies.",hds:false},
  {id:"A.5.11",d:"A5",t:"Restitution des actifs",desc:"Actifs restitués à la cessation d'emploi.",hds:false},
  {id:"A.5.12",d:"A5",t:"Classification de l'information",desc:"Information classifiée selon les besoins de sécurité.",hds:true},
  {id:"A.5.13",d:"A5",t:"Marquage de l'information",desc:"Procédures de marquage conformes à la classification.",hds:false},
  {id:"A.5.14",d:"A5",t:"Transfert de l'information",desc:"Règles et contrôles pour le transfert d'information.",hds:true},
  {id:"A.5.15",d:"A5",t:"Contrôle d'accès",desc:"Politique de contrôle d'accès établie et revue selon les risques.",hds:true},
  {id:"A.5.16",d:"A5",t:"Gestion des identités",desc:"Cycle de vie complet de gestion des identités maîtrisé.",hds:true},
  {id:"A.5.17",d:"A5",t:"Informations d'authentification",desc:"Informations secrètes d'authentification gérées.",hds:true},
  {id:"A.5.18",d:"A5",t:"Droits d'accès",desc:"Droits d'accès provisionnés, révoqués et revus.",hds:true},
  {id:"A.5.19",d:"A5",t:"SSI dans les relations fournisseurs",desc:"Processus de gestion de la sécurité avec les fournisseurs.",hds:true},
  {id:"A.5.20",d:"A5",t:"SSI dans les contrats fournisseurs",desc:"Exigences SSI dans les accords fournisseurs.",hds:true},
  {id:"A.5.21",d:"A5",t:"Chaîne d'approvisionnement TIC",desc:"Sécurité dans la chaîne d'approvisionnement TIC.",hds:true},
  {id:"A.5.22",d:"A5",t:"Suivi fournisseurs",desc:"Prestation des fournisseurs surveillée, revue et auditée.",hds:false},
  {id:"A.5.23",d:"A5",t:"SSI services cloud",desc:"Sécurité lors de l'utilisation de services cloud.",hds:true},
  {id:"A.5.24",d:"A5",t:"Gestion des incidents SSI",desc:"Gestion des incidents SSI planifiée et préparée.",hds:true},
  {id:"A.5.25",d:"A5",t:"Évaluation des incidents",desc:"Événements SSI évalués et classifiés.",hds:false},
  {id:"A.5.26",d:"A5",t:"Réponse aux incidents",desc:"Incidents SSI traités selon procédures documentées.",hds:true},
  {id:"A.5.27",d:"A5",t:"Retour d'expérience",desc:"Incidents utilisés pour améliorer les contrôles.",hds:false},
  {id:"A.5.28",d:"A5",t:"Collecte de preuves",desc:"Procédures pour identification et collecte de preuves.",hds:false},
  {id:"A.5.29",d:"A5",t:"SSI en situation de crise",desc:"SSI planifiée pendant les perturbations.",hds:true},
  {id:"A.5.30",d:"A5",t:"Continuité TIC",desc:"Continuité TIC préparée, mise en œuvre et testée.",hds:true},
  {id:"A.5.31",d:"A5",t:"Exigences légales",desc:"Exigences légales, réglementaires et contractuelles identifiées.",hds:true},
  {id:"A.5.32",d:"A5",t:"Droits de propriété intellectuelle",desc:"Droits de propriété intellectuelle protégés.",hds:false},
  {id:"A.5.33",d:"A5",t:"Protection des enregistrements",desc:"Enregistrements protégés contre perte et falsification.",hds:true},
  {id:"A.5.34",d:"A5",t:"Confidentialité et données personnelles",desc:"Protection des données personnelles conforme à la réglementation.",hds:true},
  {id:"A.5.35",d:"A5",t:"Revue indépendante SSI",desc:"Revue indépendante de la politique SSI.",hds:false},
  {id:"A.5.36",d:"A5",t:"Conformité aux politiques",desc:"Conformité aux politiques et normes SSI régulièrement vérifiée.",hds:false},
  {id:"A.5.37",d:"A5",t:"Procédures d'exploitation documentées",desc:"Procédures d'exploitation documentées et disponibles.",hds:false},
  {id:"A.6.1",d:"A6",t:"Filtrage",desc:"Antécédents des candidats vérifiés avant embauche.",hds:false},
  {id:"A.6.2",d:"A6",t:"Conditions d'emploi",desc:"Engagements contractuels SSI inclus dans les contrats.",hds:false},
  {id:"A.6.3",d:"A6",t:"Sensibilisation et formation",desc:"Programme de sensibilisation et formation SSI en place.",hds:true},
  {id:"A.6.4",d:"A6",t:"Processus disciplinaire",desc:"Processus disciplinaire formalisé pour violations SSI.",hds:false},
  {id:"A.6.5",d:"A6",t:"Cessation ou changement d'emploi",desc:"Responsabilités SSI gérées lors de fin ou changement de contrat.",hds:false},
  {id:"A.6.6",d:"A6",t:"Accords de confidentialité",desc:"NDA signés par le personnel et les partenaires.",hds:true},
  {id:"A.6.7",d:"A6",t:"Travail à distance",desc:"Mesures de sécurité pour le travail à distance.",hds:false},
  {id:"A.6.8",d:"A6",t:"Signalement des événements",desc:"Mécanisme de signalement des événements SSI opérationnel.",hds:false},
  {id:"A.7.1",d:"A7",t:"Périmètres de sécurité physique",desc:"Périmètres physiques sécurisés définis pour les zones sensibles.",hds:true},
  {id:"A.7.2",d:"A7",t:"Contrôles d'accès physique",desc:"Zones sécurisées protégées par contrôles d'accès.",hds:true},
  {id:"A.7.3",d:"A7",t:"Sécurisation des bureaux",desc:"Sécurité physique des bureaux et locaux.",hds:false},
  {id:"A.7.4",d:"A7",t:"Surveillance physique",desc:"Zones physiques sensibles surveillées en permanence.",hds:true},
  {id:"A.7.5",d:"A7",t:"Protection menaces physiques",desc:"Protection contre les menaces physiques et environnementales.",hds:false},
  {id:"A.7.6",d:"A7",t:"Travail en zones sécurisées",desc:"Procédures de travail dans les zones sécurisées.",hds:false},
  {id:"A.7.7",d:"A7",t:"Bureau propre et écran vide",desc:"Politique bureau propre et écran vide appliquée.",hds:false},
  {id:"A.7.8",d:"A7",t:"Emplacement et protection des équipements",desc:"Équipements sécurisés contre les risques environnementaux.",hds:true},
  {id:"A.7.9",d:"A7",t:"Sécurité hors des locaux",desc:"Équipements hors locaux protégés.",hds:false},
  {id:"A.7.10",d:"A7",t:"Supports de stockage",desc:"Cycle de vie des supports de stockage maîtrisé.",hds:true},
  {id:"A.7.11",d:"A7",t:"Énergie et réseaux de support",desc:"Alimentation et réseaux de support protégés.",hds:true},
  {id:"A.7.12",d:"A7",t:"Sécurité du câblage",desc:"Câblage protégé contre interception et dommages.",hds:false},
  {id:"A.7.13",d:"A7",t:"Maintenance des équipements",desc:"Équipements maintenus correctement et de façon sécurisée.",hds:false},
  {id:"A.7.14",d:"A7",t:"Mise au rebut ou réutilisation",desc:"Données détruites avant mise au rebut ou réutilisation.",hds:true},
  {id:"A.8.1",d:"A8",t:"Équipements des utilisateurs",desc:"Informations stockées sur équipements utilisateurs protégées.",hds:false},
  {id:"A.8.2",d:"A8",t:"Droits d'accès privilégiés",desc:"Droits d'accès privilégiés restreints et gérés.",hds:true},
  {id:"A.8.3",d:"A8",t:"Restrictions d'accès à l'information",desc:"Accès à l'information restreint selon la politique.",hds:true},
  {id:"A.8.4",d:"A8",t:"Accès au code source",desc:"Accès au code source et outils de développement géré.",hds:false},
  {id:"A.8.5",d:"A8",t:"Authentification sécurisée",desc:"Technologies d'authentification sécurisée mises en œuvre.",hds:true},
  {id:"A.8.6",d:"A8",t:"Gestion de la capacité",desc:"Capacités surveillées et ajustées pour répondre aux besoins.",hds:false},
  {id:"A.8.7",d:"A8",t:"Protection contre les malwares",desc:"Protection contre les malwares mise en œuvre et maintenue.",hds:true},
  {id:"A.8.8",d:"A8",t:"Gestion des vulnérabilités techniques",desc:"Vulnérabilités techniques identifiées et traitées en temps opportun.",hds:true},
  {id:"A.8.9",d:"A8",t:"Gestion de la configuration",desc:"Configurations sécurisées établies, documentées et surveillées.",hds:true},
  {id:"A.8.10",d:"A8",t:"Suppression de l'information",desc:"Informations inutiles supprimées des systèmes et supports.",hds:true},
  {id:"A.8.11",d:"A8",t:"Masquage des données",desc:"Données sensibles masquées selon la politique.",hds:true},
  {id:"A.8.12",d:"A8",t:"Prévention des fuites de données",desc:"Mesures DLP pour prévenir divulgation non autorisée.",hds:true},
  {id:"A.8.13",d:"A8",t:"Sauvegarde de l'information",desc:"Information, logiciels et systèmes sauvegardés selon la politique.",hds:true},
  {id:"A.8.14",d:"A8",t:"Redondance des équipements",desc:"Redondance suffisante pour les exigences de disponibilité.",hds:true},
  {id:"A.8.15",d:"A8",t:"Journalisation",desc:"Journaux d'événements produits, protégés et analysés.",hds:true},
  {id:"A.8.16",d:"A8",t:"Activités de surveillance",desc:"Réseaux, systèmes et applications surveillés.",hds:true},
  {id:"A.8.17",d:"A8",t:"Synchronisation des horloges",desc:"Horloges des systèmes de traitement synchronisées.",hds:false},
  {id:"A.8.18",d:"A8",t:"Utilisation de programmes utilitaires",desc:"Programmes utilitaires pouvant contourner les contrôles maîtrisés.",hds:false},
  {id:"A.8.19",d:"A8",t:"Installation de logiciels en production",desc:"Installation de logiciels en production sécurisée et maîtrisée.",hds:false},
  {id:"A.8.20",d:"A8",t:"Sécurité des réseaux",desc:"Réseaux sécurisés et gérés pour protéger l'information.",hds:true},
  {id:"A.8.21",d:"A8",t:"Sécurité des services réseau",desc:"Mécanismes de sécurité des services réseau identifiés et mis en œuvre.",hds:true},
  {id:"A.8.22",d:"A8",t:"Cloisonnement des réseaux",desc:"Groupes de services, utilisateurs et systèmes séparés.",hds:true},
  {id:"A.8.23",d:"A8",t:"Filtrage web",desc:"Accès aux sites web externes gérés.",hds:false},
  {id:"A.8.24",d:"A8",t:"Utilisation de la cryptographie",desc:"Règles cryptographiques établies, clés gérées.",hds:true},
  {id:"A.8.25",d:"A8",t:"Cycle de vie de développement sécurisé",desc:"Règles de développement sécurisé dans le SDLC.",hds:false},
  {id:"A.8.26",d:"A8",t:"Exigences de sécurité applicatives",desc:"Exigences de sécurité applicatives identifiées et approuvées.",hds:false},
  {id:"A.8.27",d:"A8",t:"Architecture sécurisée",desc:"Principes d'ingénierie système sécurisée appliqués.",hds:false},
  {id:"A.8.28",d:"A8",t:"Codage sécurisé",desc:"Principes de codage sécurisé appliqués dans le développement.",hds:false},
  {id:"A.8.29",d:"A8",t:"Tests de sécurité",desc:"Sécurité testée tout au long du processus de développement.",hds:false},
  {id:"A.8.30",d:"A8",t:"Développement externalisé",desc:"Activités de développement externalisé contrôlées.",hds:false},
  {id:"A.8.31",d:"A8",t:"Séparation des environnements",desc:"Environnements de développement, test et production séparés.",hds:false},
  {id:"A.8.32",d:"A8",t:"Gestion des changements",desc:"Changements aux ressources de traitement contrôlés.",hds:false},
  {id:"A.8.33",d:"A8",t:"Informations de test",desc:"Informations de test sélectionnées, protégées et gérées.",hds:false},
  {id:"A.8.34",d:"A8",t:"Protection des systèmes en audit",desc:"Tests d'audit en production planifiés et protégés.",hds:false},
];

window.ISO_AUDIT_DOMAINS = [
  {id:"4",label:"§4 Contexte",group:"Clauses ISO 27001"},
  {id:"5",label:"§5 Leadership",group:"Clauses ISO 27001"},
  {id:"6",label:"§6 Planification",group:"Clauses ISO 27001"},
  {id:"7",label:"§7 Support",group:"Clauses ISO 27001"},
  {id:"8",label:"§8 Fonctionnement",group:"Clauses ISO 27001"},
  {id:"9",label:"§9 Évaluation",group:"Clauses ISO 27001"},
  {id:"10",label:"§10 Amélioration",group:"Clauses ISO 27001"},
  {id:"A5",label:"A.5 Organisationnels",group:"Annexe A"},
  {id:"A6",label:"A.6 RH",group:"Annexe A"},
  {id:"A7",label:"A.7 Physique",group:"Annexe A"},
  {id:"A8",label:"A.8 Technologique",group:"Annexe A"},
];

window.ISO_AUDIT_QUESTIONS = {
  "4.1":["Pouvez-vous me presenter le document d'analyse du contexte strategique de l'organisme ?","Quelles sont les principales menaces exterieures identifiees pour le SI ?","Comment les enjeux internes (culture, ressources, structure) sont-ils pris en compte dans le SMSI ?"],
  "4.2":["Qui sont les parties interessees du SMSI et comment ont-elles ete identifiees ?","Comment les exigences de ces parties sont-elles documentees et suivies ?","Une revue de ces parties est-elle realisee periodiquement ?"],
  "4.3":["Quel est le perimetre exact du SMSI ? Quels systemes, sites et processus sont inclus ou exclus ?","Comment les interfaces avec des systemes hors perimetre sont-elles gerees ?","La declaration de perimetre est-elle approuvee et a jour ?"],
  "4.4":["L'SMSI est-il documente ? Existe-t-il un manuel ou une politique cadre SMSI ?","Quels processus de management sont en place pour maintenir et ameliorer le SMSI ?"],
  "5.1":["La direction a-t-elle formellement approuve la politique SSI ? Sous quelle forme ?","Comment la direction demontre-t-elle son engagement concret (budget, revue, arbitrages) ?","La SSI est-elle integree dans les objectifs strategiques de l'organisme ?"],
  "5.2":["Pouvez-vous me montrer la politique de securite de l'information ?","Quand a-t-elle ete approuvee et par qui ? Est-elle a jour ?","Comment est-elle communiquee au personnel ? Tous les employes y ont-ils acces ?"],
  "5.3":["Qui est le RSSI ou responsable SSI ? Quelles sont ses missions et son autorite ?","Comment les responsabilites SSI sont-elles documentees et communiquees ?","Existe-t-il une organisation formelle de la SSI (comite, roles) ?"],
  "6.1":["Quelle methode d'appreciation des risques utilisez-vous ?","Quand la derniere appreciation des risques a-t-elle ete realisee ?","Comment les risques sont-ils priorises et quels sont les criteres d'acceptation ?"],
  "6.1.2":["Pouvez-vous me montrer le registre des risques SSI ?","Comment les actifs, menaces et vulnerabilites sont-ils identifies ?","Qui valide les resultats de l'appreciation des risques ?"],
  "6.1.3":["Pouvez-vous me montrer la Declaration d'Applicabilite (SoA) ?","Comment les mesures de traitement ont-elles ete selectionnees ?","Les risques residuels ont-ils ete acceptes formellement par la direction ?"],
  "6.2":["Quels sont les objectifs de securite de l'information pour cette annee ?","Comment sont-ils mesures et suivis ?","Sont-ils alignes avec la politique SSI ?"],
  "7.1":["Quelles ressources (humaines, financieres, techniques) sont allouees au SMSI ?","Disposez-vous d'un budget SSI formalise ?","Les ressources sont-elles jugees suffisantes par le RSSI ?"],
  "7.2":["Quelles competences SSI sont requises dans votre organisation ?","Comment les competences du personnel sont-elles evaluees et maintenues ?","Pouvez-vous me montrer les CV ou certifications des referents SSI ?"],
  "7.3":["Comment le personnel est-il sensibilise a la politique SSI ?","A quelle frequence les actions de sensibilisation sont-elles realisees ?","Comment mesurez-vous l'efficacite de la sensibilisation ?"],
  "7.4":["Comment la communication interne sur la SSI est-elle organisee ?","Existe-t-il un canal pour que les employes remontent les problemes SSI ?","Comment communiquez-vous avec les parties externes sur les sujets SSI ?"],
  "7.5":["Pouvez-vous me montrer la liste des documents requis par le SMSI ?","Comment la gestion documentaire est-elle organisee (versionning, approbation) ?","Comment assurez-vous que les employes disposent des versions a jour ?"],
  "8.1":["Comment les processus operationnels SSI sont-ils planifies et surveilles ?","Existe-t-il des indicateurs de performance operationnelle SSI ?","Comment les changements sont-ils geres dans le SMSI ?"],
  "8.2":["A quelle frequence realisez-vous des appreciations des risques ?","Quelle a ete la derniere ? Pouvez-vous me montrer le rapport ?","Les resultats ont-ils conduit a des modifications des mesures ?"],
  "8.3":["Le plan de traitement des risques est-il suivi ? Pouvez-vous me le montrer ?","Quels risques restent non traites et pourquoi ?","Qui pilote la mise en oeuvre du plan de traitement ?"],
  "9.1":["Quels indicateurs de performance SSI suivez-vous ?","A quelle frequence sont-ils mesures et rapportes ?","Comment ces mesures sont-elles utilisees pour ameliorer le SMSI ?"],
  "9.2":["Pouvez-vous me montrer le programme d'audit interne ?","Quand a eu lieu le dernier audit interne complet ?","Comment les ecarts identifies lors des audits sont-ils traites ?"],
  "9.3":["Quand a eu lieu la derniere revue de direction du SMSI ?","Pouvez-vous me montrer le compte-rendu ? Quels sujets ont ete traites ?","Quelles decisions ont ete prises lors de cette revue ?"],
  "10.1":["Comment les non-conformites SSI sont-elles identifiees et enregistrees ?","Pouvez-vous me montrer des exemples d'actions correctives recentes ?","Comment l'efficacite des actions correctives est-elle verifiee ?"],
  "10.2":["Quelles initiatives d'amelioration continue du SMSI sont en cours ?","Comment les retours d'experience (incidents, audits) alimentent-ils l'amelioration ?","Quels progres observez-vous par rapport a l'audit precedent ?"],
  "A.5.1":["Pouvez-vous me montrer l'ensemble des politiques SSI en vigueur ?","Quand ont-elles ete revues pour la derniere fois ? Par qui ?","Comment sont-elles accessibles au personnel ? Sont-elles connues ?"],
  "A.5.2":["Qui est designe comme responsable SSI ou RSSI ? Depuis quand ?","Les responsabilites SSI sont-elles formellement documentees (fiche de poste, charte) ?","Comment les responsabilites sont-elles communiquees a l'ensemble du personnel ?","Existe-t-il une structure de gouvernance SSI (comite, instance de pilotage) ?"],
  "A.5.3":["Comment les taches incompatibles sont-elles identifiees (ex: demande et approbation acces) ?","Existe-t-il des controles compensatoires la ou la separation n'est pas possible ?","Un exemple concret de separation de taches appliquee ?"],
  "A.5.4":["Comment la direction s'assure-t-elle que le personnel respecte la politique SSI ?","Des rappels ou communications de la direction sur la SSI ont-ils lieu regulierement ?","Que se passe-t-il lorsqu'un employe ne respecte pas les regles SSI ?"],
  "A.5.5":["Quels sont les contacts etablis avec les autorites (ANSSI, CNIL, ARS, CERT-FR) ?","Comment ces contacts sont-ils actives en cas d'incident majeur ?","Existe-t-il une procedure de notification aux autorites en cas de violation de donnees ?"],
  "A.5.6":["L'organisme est-il membre de groupes specialises SSI (CESIN, CLUSIF, secteur sante) ?","Comment les informations issues de ces groupes sont-elles exploitees en interne ?","Des echanges avec des pairs sur les menaces sectorielles ont-ils lieu ?"],
  "A.5.7":["Quelles sources de threat intelligence sont utilisees (CERT-FR, ANSSI, ISACs) ?","Comment les informations sur les menaces sont-elles collectees et analysees ?","Un processus formel de veille sur les menaces est-il en place ? Qui en est responsable ?","Les renseignements sur les menaces alimentent-ils la mise a jour de l'analyse des risques ?"],
  "A.5.8":["Comment la SSI est-elle integree dans le processus de gestion de projet ?","Existe-t-il une liste de controles SSI a verifier lors du lancement d'un projet ?","Les projets IT font-ils l'objet d'une analyse de risques SSI avant mise en production ?","Le RSSI est-il associe aux projets des leur phase de conception ?"],
  "A.5.9":["Pouvez-vous me montrer l'inventaire des actifs informationnels ?","Comment est-il maintenu a jour ? A quelle frequence est-il revise ?","Chaque actif a-t-il un proprietaire designe ?"],
  "A.5.10":["Existe-t-il une politique d'utilisation acceptable des equipements et des donnees ?","Cette politique est-elle signee par les employes et les prestataires ?","Comment l'utilisation non autorisee des actifs est-elle detectee et traitee ?"],
  "A.5.11":["Quel est le processus de restitution des equipements lors d'un depart ?","Comment s'assure-t-on que toutes les donnees sont effacees des equipements personnels ?","Les acces logiques sont-ils revoques en meme temps que la restitution des equipements ?"],
  "A.5.12":["Quels sont les niveaux de classification utilises ?","Pouvez-vous me montrer un exemple de document classifie ?","Comment la classification est-elle attribuee et revue ?"],
  "A.5.13":["Comment les documents sont-ils marques selon leur niveau de classification ?","Le marquage est-il applique aux documents numeriques et physiques ?","Les employes sont-ils formes au marquage des documents ?"],
  "A.5.14":["Quelles sont les regles de transfert d'information (email, USB, cloud) ?","Comment les transferts vers des tiers sont-ils securises ?","Les accords de confidentialite couvrent-ils les transferts d'information ?"],
  "A.5.15":["Pouvez-vous me montrer la politique de controle d'acces ?","Comment les acces sont-ils provisonnes et revoques (arrivee/depart) ?","Quand la derniere revue des droits a-t-elle ete realisee ?"],
  "A.5.16":["Quel est le processus de gestion du cycle de vie des identites ?","Comment les comptes orphelins sont-ils detectes et desactives ?","Les comptes generiques ou partages sont-ils autorises ? Sous quelles conditions ?"],
  "A.5.17":["Existe-t-il une politique de gestion des mots de passe ?","Comment la robustesse des mots de passe est-elle verifiee ?","Les secrets d'authentification sont-ils stockes de facon securisee ?"],
  "A.5.18":["Comment les droits d'acces sont-ils revus periodiquement ?","Qui autorise les acces privilegies ? Existe-t-il un processus formel ?","Les acces sont-ils bases sur le principe du moindre privilege ?"],
  "A.5.19":["Existe-t-il une politique de securite pour les fournisseurs ?","Comment les fournisseurs sont-ils evalues avant contractualisation ?","Les exigences SSI figurent-elles dans tous les contrats fournisseurs ?"],
  "A.5.20":["Les exigences SSI sont-elles incluses dans tous les contrats fournisseurs ?","Comment les clauses SSI sont-elles negociees et validees avant signature ?","Existe-t-il un modele de clause SSI standard pour les contrats ?"],
  "A.5.21":["Comment la securite de la chaine d'approvisionnement TIC est-elle evaluee ?","Les fournisseurs de composants logiciels et materiels sont-ils evalues sur leur securite ?","Existe-t-il une politique de gestion des risques liee a la chaine d'approvisionnement ?"],
  "A.5.22":["Comment la prestation des fournisseurs est-elle surveillee et evaluee ?","Des audits ou revues des fournisseurs sont-ils realises ? A quelle frequence ?","Comment les non-conformites fournisseurs sont-elles gerees ?"],
  "A.5.23":["Quels services cloud sont utilises ? Sont-ils inventories ?","Comment la securite des services cloud est-elle evaluee et contractualisee ?","Comment les droits et acces cloud sont-ils geres (IAM) ?"],
  "A.5.24":["Existe-t-il une procedure de gestion des incidents SSI ? Pouvez-vous me la montrer ?","Comment les incidents sont-ils declares et escalades ?","Un exercice de simulation a-t-il ete realise recemment ?"],
  "A.5.25":["Comment les evenements SSI sont-ils evalues pour determiner s'ils constituent un incident ?","Qui est habilite a declarer un incident SSI ? Quel est le seuil de declenchement ?","Existe-t-il une grille de classification de la severite des incidents ?"],
  "A.5.26":["Pouvez-vous decrire la derniere reponse a un incident SSI significatif ?","Les etapes de confinement, eradication et retablissement sont-elles documentees ?","Comment les preuves sont-elles preservees lors d'un incident ?"],
  "A.5.27":["Comment les incidents SSI passes sont-ils analyses pour en tirer des enseignements ?","Les retours d'experience sont-ils documentes et partages avec les equipes ?","Les incidents ont-ils conduit a des modifications des controles SSI ?"],
  "A.5.28":["Existe-t-il une procedure de collecte et preservation des preuves numeriques ?","Les preuves sont-elles collectees de maniere a garantir leur integrite (chaine de custody) ?","Le personnel est-il forme aux techniques de base de preservation des preuves ?"],
  "A.5.29":["Existe-t-il un plan de continuite d'activite prenant en compte la SSI ?","Comment la securite de l'information est-elle maintenue en cas de crise ?","Le plan a-t-il ete teste ? Quand ?"],
  "A.5.30":["Existe-t-il un plan de continuite informatique (PCI/DRP) ?","Les RTO et RPO sont-ils definis et contractualises pour les systemes critiques ?","Quand le plan a-t-il ete teste pour la derniere fois ? Avec quels resultats ?"],
  "A.5.31":["Pouvez-vous me montrer le registre des exigences legales et reglementaires ?","Comment les nouvelles obligations (NIS2, RGPD, HDS) sont-elles integrees ?","Comment la conformite legale est-elle verifiee periodiquement ?"],
  "A.5.32":["Comment les droits de propriete intellectuelle sont-ils geres (licences logicielles) ?","Existe-t-il un inventaire des licences logicielles ? Est-il a jour ?","Comment l'utilisation de logiciels non licencies est-elle detectee et traitee ?"],
  "A.5.33":["Comment les enregistrements critiques sont-ils proteges contre la perte et la falsification ?","Quelle est la politique de retention des enregistrements SSI (durees legales) ?","Les sauvegardes des enregistrements sont-elles testees ?"],
  "A.5.34":["Existe-t-il un registre des traitements de donnees personnelles ?","Comment le RGPD est-il mis en oeuvre dans le SI (minimisation, droits des personnes) ?","Qui est le DPO et quel est son perimetre d'intervention ?"],
  "A.5.35":["Des revues independantes de la securite de l'information sont-elles realisees ?","Par qui ces revues sont-elles effectuees (interne independant ou auditeur externe) ?","Quels sont les derniers resultats et recommandations issus de ces revues ?"],
  "A.5.36":["Comment la conformite aux politiques et normes SSI est-elle verifiee regulierement ?","Des auto-evaluations ou check-lists de conformite sont-elles utilisees ?","Les resultats des verifications de conformite sont-ils reportes a la direction ?"],
  "A.5.37":["Quelles procedures d'exploitation sont documentees (sauvegarde, monitoring, incidents) ?","Ces procedures sont-elles accessibles aux personnes qui en ont besoin ?","A quelle frequence sont-elles revues et mises a jour ?"],
  "A.6.1":["Comment les antecedents des candidats sont-ils verifies avant l'embauche ?","Cette verification inclut-elle les prestataires et les interimaires ?","Quelles sont les limites legales de ces verifications dans votre pays ?"],
  "A.6.2":["Les contrats de travail incluent-ils des clauses de confidentialite et de responsabilite SSI ?","Les prestataires et interimaires sont-ils soumis aux memes obligations contractuelles ?","Comment ces engagements sont-ils rappeles au personnel en cours d'emploi ?"],
  "A.6.3":["Pouvez-vous me montrer le programme de sensibilisation et formation SSI ?","A quelle frequence les actions sont-elles realisees ? Avec quel taux de participation ?","Comment l'efficacite de la sensibilisation est-elle mesuree ?"],
  "A.6.4":["Existe-t-il un processus disciplinaire formel pour les violations des politiques SSI ?","Ce processus a-t-il deja ete applique ? Dans quel type de cas ?","Le personnel est-il informe de l'existence de ce processus disciplinaire ?"],
  "A.6.5":["Quel est le processus de gestion des departs (demission, licenciement, retraite) ?","Comment s'assure-t-on que tous les acces sont revoques le jour du depart ?","Les changements de poste internes font-ils l'objet d'une revue des droits d'acces ?"],
  "A.6.6":["Tous les employes et prestataires ont-ils signe un accord de confidentialite ?","Ces accords sont-ils a jour ? Couvrent-ils les donnees de sante ?","Comment est geree la confidentialite apres depart ?"],
  "A.6.7":["Existe-t-il une politique de securite pour le travail a distance (teletravail) ?","Comment les connexions a distance sont-elles securisees (VPN, MFA) ?","Les employes en teletravail sont-ils sensibilises aux risques specifiques (shoulder surfing, wifi public) ?"],
  "A.6.8":["Comment les employes peuvent-ils signaler un evenement ou incident SSI suspect ?","Existe-t-il un canal dedie (email, hotline, formulaire) pour le signalement ?","Les employes sont-ils encourages et proteges lorsqu'ils signalent des problemes SSI ?"],
  "A.7.1":["Pouvez-vous me decrire les perimettres physiques securises (batiments, salles) ?","Comment les zones sensibles sont-elles identifiees et protegees ?","Existe-t-il un plan des zones de securite ?"],
  "A.7.2":["Quels moyens de controle d'acces physique sont en place (badges, biometrie, vigiles) ?","Comment les acces aux zones sensibles sont-ils traces et revus ?","Que se passe-t-il en cas de perte de badge ?"],
  "A.7.3":["Comment les bureaux et locaux sont-ils securises physiquement (portes, serrures) ?","Les visiteurs sont-ils accompagnes dans les zones sensibles ?","Y a-t-il des regles specifiques pour les salles de reunion (documents, ecrans visibles) ?"],
  "A.7.4":["Quels systemes de surveillance physique sont en place (cameras, alarmes) ?","Comment les alarmes sont-elles surveillees et traitees ?","Les enregistrements video sont-ils conserves suffisamment longtemps ?"],
  "A.7.5":["Quelles protections sont en place contre les menaces physiques (incendie, inondation, tremblements de terre) ?","Des plans d'evacuation et de gestion de crise physique sont-ils en place ?","Les equipements critiques sont-ils proteges contre la chaleur, l'humidite et les chocs ?"],
  "A.7.6":["Quelles regles specifiques s'appliquent au travail en zones securisees (salle serveurs, archives) ?","Le travail seul en zone securisee est-il autorise ? Sous quelles conditions ?","Les equipements photo et d'enregistrement sont-ils interdits dans les zones sensibles ?"],
  "A.7.7":["Une politique de bureau propre est-elle en vigueur ? Comment est-elle controlee ?","Les ecrans sont-ils verrouilles automatiquement apres une periode d'inactivite ?","Comment les documents imprimes sensibles sont-ils geres (dechiquetage, coffre) ?"],
  "A.7.8":["Ou sont installes les equipements sensibles ? Sont-ils proteges contre les risques environnementaux ?","Les serveurs sont-ils dans des baies fermees a cle en salle climatisee ?","Existe-t-il une protection contre la foudre et les surtensions ?"],
  "A.7.9":["Quelles mesures protegent les equipements utilises en dehors des locaux (laptop, smartphone) ?","Existe-t-il une procedure pour les equipements perdus ou voles ?","Le chiffrement est-il applique sur tous les equipements nomades ?"],
  "A.7.10":["Comment les supports de stockage (USB, disques, papier) sont-ils geres ?","Comment les supports sont-ils detruits de facon securisee (DU-SD 22/2011) ?","Existe-t-il un registre des supports sensibles ?"],
  "A.7.11":["Existe-t-il une alimentation de secours (onduleur, groupe electrogene) ?","Depuis quand n'a-t-elle pas ete testee ?","Les alimentations de secours couvrent-elles tous les systemes critiques ?"],
  "A.7.12":["Comment le cablage reseau et electrique est-il protege contre les interceptions et dommages ?","Les cables sensibles sont-ils chemines dans des goulottes fermees ou des locaux techniques securises ?","Le cablage est-il documente et etiquete ?"],
  "A.7.13":["Quel est le programme de maintenance preventive des equipements critiques ?","Les maintenances sont-elles realisees par du personnel habilite et tracees ?","Comment la securite est-elle maintenue lors d'interventions de maintenance (presence, supervision) ?"],
  "A.7.14":["Quelle procedure est en place avant mise au rebut ou reutilisation d'un equipement ?","Comment les donnees sont-elles effacees ? Utilisez-vous des outils certifies ?","Ces operations sont-elles tracees ?"],
  "A.8.1":["Quelles mesures protegent les donnees sur les postes de travail des utilisateurs (chiffrement, verrouillage) ?","Existe-t-il une politique BYOD ? Comment les terminaux personnels sont-ils geres ?","Les postes de travail sont-ils configures avec des profils de securite durcis ?"],
  "A.8.2":["Comment les droits d'acces privilegies (admin, root) sont-ils geres ?","Qui dispose de comptes privilegies ? Cette liste est-elle revue regulierement ?","Les acces privilegies sont-ils traces et surveilles ?"],
  "A.8.3":["Comment les restrictions d'acces a l'information sont-elles implementees techniquement ?","Le principe du moindre privilege est-il applique systematiquement ?","Des revues d'acces sont-elles realisees pour verifier la conformite aux droits attribues ?"],
  "A.8.4":["Comment l'acces au code source et aux outils de developpement est-il controle ?","Le code source est-il stocke dans un depot securise avec gestion des acces ?","Les developpeurs ont-ils acces au code de production ? Sous quelles conditions ?"],
  "A.8.5":["Quelle solution d'authentification est deployee ? MFA en place ?","Sur quels systemes le MFA est-il applique (VPN, cloud, admin) ?","Existe-t-il des exceptions au MFA ? Pour quelles raisons ?"],
  "A.8.6":["Comment la capacite des systemes (stockage, CPU, memoire, bande passante) est-elle surveillee ?","Des alertes sont-elles declenchees avant d'atteindre les seuils critiques ?","Comment les besoins futurs en capacite sont-ils anticipes et planifies ?"],
  "A.8.7":["Quelle solution antimalware est deployee ? Sur quels equipements ?","Comment est-elle maintenue a jour ? A quelle frequence les bases sont-elles mises a jour ?","Des incidents malware ont-ils eu lieu recemment ?"],
  "A.8.8":["Pouvez-vous me montrer le dernier rapport de scan de vulnerabilites ?","Quelle est la procedure de patch management ? Quels sont les delais de correction ?","Comment les vulnerabilites critiques sont-elles priorisees ?"],
  "A.8.9":["Existe-t-il des configurations de base durcies (hardening) pour les equipements ?","Ces configurations sont-elles documentees et appliquees systematiquement ?","Comment la derive de configuration est-elle detectee ?"],
  "A.8.10":["Quelle est la procedure de suppression securisee des donnees en fin de vie ?","La suppression s'applique-t-elle aux sauvegardes, archives et bases de donnees de test ?","Les suppressions sont-elles tracees et certifiees ?"],
  "A.8.11":["Des techniques de masquage, anonymisation ou pseudonymisation sont-elles utilisees ?","Sur quelles donnees ces techniques sont-elles appliquees (tests, analytics, exports) ?","La politique de masquage est-elle documentee et controlee ?"],
  "A.8.12":["Des outils DLP sont-ils en place ? Sur quels canaux (email, USB, impression) ?","Comment les flux de donnees sensibles sont-ils surveilles ?","Des incidents de fuite de donnees ont-ils ete detectes ?"],
  "A.8.13":["Pouvez-vous me montrer la politique de sauvegarde ?","Quand le dernier test de restauration a-t-il ete realise ? Avec quels resultats ?","Les sauvegardes sont-elles hors site et chiffrees ?"],
  "A.8.14":["Quels sont les mecanismes de redondance en place (cluster, failover, load balancing) ?","Les SLA de disponibilite sont-ils definis et mesures ?","La redondance a-t-elle ete testee recemment (bascule) ?"],
  "A.8.15":["Quels evenements sont journalises (authentification, acces, erreurs, admin) ?","Quelle est la duree de conservation des journaux ?","Qui analyse les journaux et a quelle frequence ? Existe-t-il des alertes automatiques ?"],
  "A.8.16":["Quels outils de surveillance reseau et systeme sont en place (SIEM, SOC) ?","Comment les alertes sont-elles traitees ? Qui en est responsable ?","Les activites anormales sont-elles correlees entre differents systemes ?"],
  "A.8.17":["Comment les horloges des systemes de traitement sont-elles synchronisees ?","Un serveur NTP de reference est-il utilise ? Est-il securise ?","La synchronisation des horloges est-elle verifiee regulierement pour la tracabilite des logs ?"],
  "A.8.18":["Quels programmes utilitaires privilegies sont autorises (outils d'administration, debuggers) ?","Comment leur utilisation est-elle autorisee et tracee ?","Existe-t-il une liste blanche des outils autorises en environnement de production ?"],
  "A.8.19":["Quelle est la procedure d'installation de logiciels en environnement de production ?","Qui est habilite a installer des logiciels en production ?","Les installations sont-elles tracees et validees par une autorite ?"],
  "A.8.20":["Pouvez-vous me montrer le schema d'architecture reseau ?","Comment les reseaux sont-ils segmentes (VLAN, DMZ, zone de confiance) ?","Comment le trafic reseau est-il filtre et surveille (pare-feu, IDS/IPS) ?"],
  "A.8.21":["Comment la securite des services reseau (DNS, DHCP, NTP, SMTP) est-elle assuree ?","Les services reseau sont-ils documentes et leur configuration revue periodiquement ?","Des mecanismes d'authentification et de chiffrement sont-ils appliques aux services reseau ?"],
  "A.8.22":["Comment les reseaux sensibles (donnees de sante, admin) sont-ils isoles ?","Les regles de pare-feu sont-elles documentees et revues periodiquement ?","Comment les acces distants sont-ils securises (VPN, bastion) ?"],
  "A.8.23":["Existe-t-il un filtrage des acces web sortants (proxy, liste blanche/noire) ?","Comment les categories de sites dangereux ou non professionnels sont-elles bloquees ?","Les regles de filtrage web sont-elles revues et mises a jour regulierement ?"],
  "A.8.24":["Existe-t-il une politique d'utilisation de la cryptographie ?","Quels algorithmes et longueurs de cle sont utilises ? Sont-ils conformes ANSSI ?","Comment les cles de chiffrement sont-elles generees, stockees et revoquees ?"],
  "A.8.25":["Un cycle de developpement securise (SSDLC) est-il en place ?","La securite est-elle integree des la phase de conception (Security by Design) ?","Les developpeurs sont-ils formes aux bonnes pratiques de developpement securise (OWASP) ?"],
  "A.8.26":["Comment les exigences de securite des applications sont-elles definies et validees ?","Existe-t-il des user stories ou criteres d'acceptance SSI dans les backlogs ?","Les exigences de securite incluent-elles la protection contre les attaques courantes (injection, XSS, CSRF) ?"],
  "A.8.27":["Des principes d'architecture securisee sont-ils documentes et appliques ?","Le principe de Defense in Depth est-il applique dans les architectures systemes ?","Comment la securite est-elle prise en compte dans les choix d'architecture cloud et hybride ?"],
  "A.8.28":["Des standards de codage securise sont-ils definis et appliques (OWASP, CERT) ?","Les revues de code incluent-elles une verification de la securite ?","Des outils d'analyse statique (SAST) ou dynamique (DAST) sont-ils utilises ?"],
  "A.8.29":["Des tests de securite sont-ils realises avant mise en production (pentest, tests intrusifs) ?","A quel moment du cycle de developpement les tests de securite sont-ils realises ?","Les vulnerabilites identifiees lors des tests sont-elles tracees et corrigees avant livraison ?"],
  "A.8.30":["Comment la securite du developpement externalise est-elle contractualisee et controlee ?","Des audits de code ou tests d'intrusion sont-ils realises sur les livrables externes ?","Les droits de propriete intellectuelle et de revue du code source sont-ils garantis contractuellement ?"],
  "A.8.31":["Les environnements de developpement, test et production sont-ils strictement separes ?","Comment s'assure-t-on qu'aucune donnee de production n'est utilisee en environnement de test ?","Les acces entre environnements sont-ils controles et traces ?"],
  "A.8.32":["Existe-t-il un processus formel de gestion des changements (change management) ?","Comment les changements en production sont-ils evalues, autorises et traces ?","Des procedures de rollback sont-elles definies en cas d'echec d'un changement ?"],
  "A.8.33":["Comment les donnees utilisees en environnement de test sont-elles selectionnees et protegees ?","Des donnees de production anonymisees ou synthetiques sont-elles utilisees pour les tests ?","Les acces aux donnees de test sensibles sont-ils controles ?"],
  "A.8.34":["Comment les audits et tests sur les systemes en production sont-ils planifies et autorises ?","Des mesures sont-elles en place pour eviter que les tests d'audit n'impactent la production ?","Les acces accordes pour les audits sont-ils limites dans le temps et revoques apres usage ?"],
};
